repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml

-   repo: local
    hooks:
    -   id: detect-custom-tokens
        name: detect custom tokens
        description: Detect application specific tokens and secrets
        entry: .pre-commit-hooks/detect_custom_tokens.py
        language: python
        types: [text]
        stages: [pre-commit]
    -   id: detect-print-statements
        name: detect print statements
        description: Detect print statements in Python files
        entry: .pre-commit-hooks/detect_print_statements.py
        language: python
        types: [python]
        stages: [pre-commit]

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)

-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests]

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        args: [
            --remove-all-unused-imports,
            --in-place,
            --recursive
        ]
        stages: [pre-commit]
    -   id: autoflake
        name: autoflake-ci-check
        args: [
            --remove-all-unused-imports,
            --check,
            --recursive
        ]
        stages: [manual]

-   repo: local
    hooks:
    -   id: run-staged-tests
        name: run unit tests for staged files
        entry: .pre-commit-hooks/run_staged_tests.py
        language: python
        pass_filenames: false
        always_run: true
