repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml

-   repo: local
    hooks:
    -   id: detect-custom-tokens
        name: detect custom tokens
        description: Detect application specific tokens and secrets
        entry: .pre-commit-hooks/detect_custom_tokens.py
        language: python
        types: [text]
        stages: [pre-commit]
    -   id: detect-print-statements
        name: detect print statements
        description: Detect print statements in Python files
        entry: .pre-commit-hooks/detect_print_statements.py
        language: python
        types: [python]
        stages: [pre-commit]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
    -   id: ruff
        name: ruff (linter)
        args: [--fix]
    -   id: ruff-format
        name: ruff (formatter)

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests]


-   repo: local
    hooks:
    -   id: run-staged-tests
        name: run unit tests for staged files
        entry: .pre-commit-hooks/run_staged_tests.py
        language: python
        pass_filenames: false
        always_run: true
