# Development docker-compose for those preferring direct docker-compose usage
# Usage: docker-compose -f docker-compose.dev.yml up
version: '3.8'

services:
  yomitalk-dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - yomitalk-data:/workspace/data
      - yomitalk-voicevox:/workspace/voicevox_core
      # Mount for git credentials
      - ~/.gitconfig:/home/vscode/.gitconfig:ro
    environment:
      - VOICEVOX_ACCEPT_AGREEMENT=true
      - PAGER=cat
      - LESSCHARSET=utf-8
      - E2E_TEST_MODE=false
      - PYTHONPATH=/workspace
    ports:
      - "7860:7860"
    # Keep container running for development
    command: sleep infinity
    # Add capabilities for audio processing if needed
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    working_dir: /workspace
    user: vscode

volumes:
  yomitalk-data:
  yomitalk-voicevox:
