# Development docker-compose for those preferring direct docker-compose usage
# Usage: docker-compose -f docker-compose.dev.yml up
version: '3.8'

services:
  yomitalk-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
      - yomitalk-data:/app/data
      - yomitalk-voicevox:/app/voicevox_core
      # Mount for git credentials
      - ~/.gitconfig:/root/.gitconfig:ro
    environment:
      - VOICEVOX_ACCEPT_AGREEMENT=true
      - PAGER=cat
      - LESSCHARSET=utf-8
      - E2E_TEST_MODE=false
      - PYTHONPATH=/app
    ports:
      - "7860:7860"
    # Keep container running for development
    command: sleep infinity
    # Add capabilities for audio processing if needed
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    working_dir: /app
    user: root

volumes:
  yomitalk-data:
  yomitalk-voicevox:
