[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_gitignore = true

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
# 既存コードへの型アノテーションを段階的に追加できるように設定を緩和
disallow_untyped_defs = false  # 型アノテーションのない関数を許可（警告）
disallow_incomplete_defs = false  # 不完全な型アノテーションを許可（警告）
check_untyped_defs = true  # 型アノテーションのない関数のボディをチェック
disallow_untyped_decorators = false  # 型アノテーションのないデコレータを許可（警告）
no_implicit_optional = true
strict_optional = true
# 将来的には下記の設定を有効にしていく
# disallow_untyped_defs = true
# disallow_incomplete_defs = true
# disallow_untyped_decorators = true

# 新規ファイルでは常に厳格に型チェック
[[tool.mypy.overrides]]
module = ["yomitalk.components.audio_generator", "yomitalk.components.pdf_uploader"]
disallow_untyped_defs = true
disallow_incomplete_defs = true

# 外部ライブラリに対しては型チェックを無視
[[tool.mypy.overrides]]
module = ["gradio.*", "PyPDF2.*", "pdfplumber.*", "transformers.*", "torch.*", "selenium.*", "ffmpeg.*", "reportlab.*", "webdriver_manager.*"]
ignore_missing_imports = true
follow_imports = "skip"

[tool.pytest.ini_options]
addopts = "--timeout=90 -v --tb=native --durations=10"
markers = [
    "slow: marks tests as slow running",
    "requires_voicevox: marks tests that require VOICEVOX Core",
    "skip: marks tests to be skipped",
    "e2e: marks end-to-end tests",
]
