version: '3.8'

services:
  yomitalk-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - yomitalk-data:/workspace/data
      - yomitalk-voicevox:/workspace/voicevox_core
    environment:
      - VOICEVOX_ACCEPT_AGREEMENT=true
      - PAGER=cat
      - LESSCHARSET=utf-8
      - E2E_TEST_MODE=false
    ports:
      - "7860:7860"
    # Keep container running for development
    command: sleep infinity
    # Add capabilities for audio processing if needed
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

volumes:
  yomitalk-data:
  yomitalk-voicevox:
