name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  VENV_PATH: ./venv
  VOICEVOX_SKIP_DOWNLOAD: true

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install linting dependencies
      run: |
        make setup-lint

    - name: Run pre-commit hooks
      run: |
        make pre-commit-run

  e2e-tests:
    runs-on: ubuntu-latest
    needs: format-check

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies and setup
      run: |
        make setup

    - name: Install Playwright browsers
      run: |
        $VENV_PATH/bin/python -m playwright install chromium

    - name: Run E2E tests
      run: |
        $VENV_PATH/bin/python -m pytest tests/e2e/ -v -s

  deploy-to-hf-spaces:
    runs-on: ubuntu-latest
    needs: e2e-tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Push to Hugging Face Space
      uses: huggingface/huggingface-push-to-spaces-action@main
      with:
        space-id: "Kyosuke0/yomitalk"
        hf-token: ${{ secrets.HF_TOKEN }}
        # リポジトリのすべてのファイルをSpaceにプッシュします
        source-directory: "."
        commit-message: "Update Space via GitHub Actions"
