name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  VENV_PATH: ./venv
  VOICEVOX_SKIP_DOWNLOAD: true
  HF_SPACE: Kyosuke0/yomitalk

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install linting dependencies
      run: |
        make setup-lint

    - name: Run pre-commit hooks
      run: |
        make pre-commit-run

  e2e-tests:
    runs-on: ubuntu-latest
    needs: format-check

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies and setup
      run: |
        make setup

    - name: Install Playwright browsers
      run: |
        $VENV_PATH/bin/python -m playwright install chromium

    - name: Run E2E tests
      run: |
        $VENV_PATH/bin/python -m pytest tests/e2e/ -v -s

  check-file-size:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3

      - name: Check large files
        uses: ActionsDesk/lfs-warning@v2.0
        with:
          filesizelimit: 10485760 # 10MB limit for HF Spaces

  deploy-to-hf:
    runs-on: ubuntu-latest
    needs: e2e-tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://Kyosuke0:$HF_TOKEN@huggingface.co/spaces/$HF_SPACE main
