name: Deploy to Hugging Face Spaces

# 手動実行のみ可能なワークフロー
on:
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: 'デプロイを確認するには "deploy" と入力してください'
        required: true
        default: ''

env:
  VENV_PATH: ./venv
  VOICEVOX_SKIP_DOWNLOAD: true
  HF_SPACE: Kyosuke0/yomitalk

jobs:
  # E2Eテスト結果の確認
  check-e2e-status:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm_deploy == 'deploy' }}
    outputs:
      last_e2e_status: ${{ steps.get_status.outputs.last_status }}
    steps:
      - name: Check recent CI workflow status
        id: get_status
        uses: actions/github-script@v6
        with:
          script: |
            const workflows = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ci.yml',
              branch: 'main',
              status: 'completed',
              per_page: 1
            });

            if (workflows.data.workflow_runs.length === 0) {
              core.setFailed('No recent CI workflow runs found');
              return;
            }

            const lastRun = workflows.data.workflow_runs[0];
            console.log(`Last CI workflow run: ${lastRun.html_url}, status: ${lastRun.conclusion}`);

            core.setOutput('last_status', lastRun.conclusion);

            if (lastRun.conclusion !== 'success') {
              core.setFailed(`最新のCIが失敗しています。E2Eテストを修復してから再試行してください。`);
              return;
            }

      - name: Notify about test status
        run: |
          echo "最新のE2Eテスト結果: ${{ steps.get_status.outputs.last_status }}"
          if [[ "${{ steps.get_status.outputs.last_status }}" != "success" ]]; then
            echo "::error::最新のE2Eテストが失敗しています。E2Eテストを修復してから再試行してください。"
            exit 1
          fi
          echo "E2Eテストは正常に完了しています。デプロイを進めます。"

  # E2Eテスト成功時のみデプロイを実行
  deploy-to-hf:
    runs-on: ubuntu-latest
    needs: check-e2e-status
    if: ${{ needs.check-e2e-status.outputs.last_e2e_status == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global http.postBuffer 524288000
          git config --global http.lowSpeedLimit 1000
          git config --global http.lowSpeedTime 300

      - name: Deploy to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "Hugging Face Spaces へデプロイを開始します..."
          git push https://Kyosuke0:$HF_TOKEN@huggingface.co/spaces/$HF_SPACE main
          echo "デプロイが完了しました！"
